title:             bratchikov.github.io
email:             bratchikov@flexberry.net
description:       A yet another blog
author:            bratchikov
baseurl:           "/"
url:               "https://bratchikov.github.io"

# Social Profiles
twitter_username:  Bratchikov_igor
github_username:   bratchikov
facebook_username: bratchikov.igor
# linkedin_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
